version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    restart: always
    ports:
      - 3307:3306
    expose:
      - 3308
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      - bridge_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart:  always
    ports:
      - 4000:8000
    volumes:
      - './backend/:/opt/backend/'
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/django.env
    depends_on:
      - database
    networks:
      - bridge_network
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 3001:3000
    expose:
      - 3000
    volumes:
      - './frontend/:/opt/frontend/'
    command: yarn start
    depends_on:
      - backend
    networks:
      - bridge_network
  redis:
    build: 
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6380:6379
    expose:
      - 6379
    networks:
      - bridge_network
  celery:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app worker -l info
    volumes:
      - ./backend/:/opt/backend
    depends_on:
      - database
      - redis
      - backend
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
    